name: Kopi CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  unit-tests:
    name: Unit Tests (Surefire)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '22'
          cache: maven

      - name: Run Unit Tests
        run: mvn -B -ntp clean test -DskipITs=true

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/*.xml
            **/target/surefire-reports/*.txt

  integration-tests:
    name: Integration Tests (Failsafe)
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '22'
          cache: maven

      # Convention: đặt test tích hợp tên đuôi *IT.java
      # Ví dụ: AuthFlowIT, CartFlowIT...
      - name: Run Integration Tests
        run: mvn -B -ntp verify -DskipTests=true

      - name: Upload Failsafe Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failsafe-reports
          path: |
            **/target/failsafe-reports/*.xml
            **/target/failsafe-reports/*.txt
